name: GenreClass
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - jupyter_client<7.0.0
  - nb_conda=2.2.1
  - numpy=1.23.5
  - python=3.8.16
  - matplotlib=3.6.2
  - scikit-learn=1.2.0
  - spacy=3.3.1
  - nltk=3.7
  - gensim=4.3.0
  - pandas=1.4.1
  - pytorch=1.12.1
  - transformers=4.24.0